-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 13:31:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Todo_Tecno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Todo_Tecno` ;

-- -----------------------------------------------------
-- Schema Todo_Tecno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Todo_Tecno` DEFAULT CHARACTER SET utf8 ;
USE `Todo_Tecno` ;

-- -----------------------------------------------------
-- Table `Todo_Tecno`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`roles` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `birthday` DATE NULL,
  `address` TEXT NULL,
  `zipCode` VARCHAR(8) NULL,
  `location` TEXT NULL,
  `province` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `roleId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `firstName` (`firstName` ASC),
  INDEX `lasName` (`lastName` ASC),
  INDEX `role_idx` (`roleId` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `role`
    FOREIGN KEY (`roleId`)
    REFERENCES `Todo_Tecno`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`categories` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`subCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`subCategories` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `categoryId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `category_idx` (`categoryId` ASC),
  CONSTRAINT `category`
    FOREIGN KEY (`categoryId`)
    REFERENCES `Todo_Tecno`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`brands` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`products` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `subCategoryId` INT(10) NOT NULL,
  `brandId` INT(10) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `artNumber` BIGINT UNSIGNED NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `discountPorc` TINYINT UNSIGNED NULL DEFAULT 0,
  `isOnSale` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `isNew` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `description` TEXT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `subCategory_idx` (`subCategoryId` ASC),
  INDEX `brand_idx` (`brandId` ASC),
  UNIQUE INDEX `artNumber_UNIQUE` (`artNumber` ASC),
  CONSTRAINT `subCategory`
    FOREIGN KEY (`subCategoryId`)
    REFERENCES `Todo_Tecno`.`subCategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brand`
    FOREIGN KEY (`brandId`)
    REFERENCES `Todo_Tecno`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`stores` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `description` TEXT NULL,
  `shoppingHours` VARCHAR(60) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`statusStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`statusStock` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`stock` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `productId` INT(10) NOT NULL,
  `storeId` INT(10) NOT NULL,
  `quantity` MEDIUMINT UNSIGNED NULL,
  `statusId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `product_idx` (`productId` ASC),
  INDEX `store_idx` (`storeId` ASC),
  INDEX `status_idx` (`statusId` ASC),
  CONSTRAINT `productOfStock`
    FOREIGN KEY (`productId`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `storeOfStock`
    FOREIGN KEY (`storeId`)
    REFERENCES `Todo_Tecno`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY (`statusId`)
    REFERENCES `Todo_Tecno`.`statusStock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`discountCupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`discountCupons` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cuponCode` VARCHAR(45) NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `discountPorcentage` TINYINT UNSIGNED NOT NULL,
  `minPurchaseRequired` DECIMAL(10,2) UNSIGNED NULL,
  `maxDiscountValue` DECIMAL(10,2) UNSIGNED NULL,
  `maxUsesPerUser` SMALLINT UNSIGNED NULL,
  `maxUsesTotal` INT UNSIGNED NULL,
  `usesCount` INT UNSIGNED NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cuponCode_UNIQUE` (`cuponCode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`statusSales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`statusSales` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`InterestOptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`InterestOptions` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `installmentsQuantity` TINYINT NOT NULL,
  `interestPorcentage` TINYINT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`paymentMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`paymentMethods` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `interestOption` INT(10) NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `interestOption_idx` (`interestOption` ASC),
  CONSTRAINT `interestOption`
    FOREIGN KEY (`interestOption`)
    REFERENCES `Todo_Tecno`.`InterestOptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`sales` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `userId` INT(10) NOT NULL,
  `chargeProducts` DECIMAL(10,2) UNSIGNED NOT NULL,
  `chargeDelivery` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0,
  `discountCuponAmount` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0,
  `chargeTotalSale` DECIMAL(10,2) GENERATED ALWAYS AS (chargeproducts+chargedelivery-discountcuponamount) VIRTUAL,
  `discountCuponId` INT(10) NULL,
  `date` DATE NOT NULL,
  `storeId` INT(10) NOT NULL,
  `paymentMethodId` INT(10) NOT NULL,
  `isPickup` TINYINT NOT NULL DEFAULT 1,
  `statusId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_idx` (`userId` ASC),
  INDEX `discountCupon_idx` (`discountCuponId` ASC),
  INDEX `store_idx` (`storeId` ASC),
  INDEX `status_idx` (`statusId` ASC),
  INDEX `paymentMethod_idx` (`paymentMethodId` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`userId`)
    REFERENCES `Todo_Tecno`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `discountCupon`
    FOREIGN KEY (`discountCuponId`)
    REFERENCES `Todo_Tecno`.`discountCupons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `storeOfSale`
    FOREIGN KEY (`storeId`)
    REFERENCES `Todo_Tecno`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `statusOfSale`
    FOREIGN KEY (`statusId`)
    REFERENCES `Todo_Tecno`.`statusSales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paymentMethod`
    FOREIGN KEY (`paymentMethodId`)
    REFERENCES `Todo_Tecno`.`paymentMethods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`detailSales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`detailSales` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `saleId` INT(10) NOT NULL,
  `productId` INT(10) NOT NULL,
  `quantity` MEDIUMINT UNSIGNED NOT NULL,
  `unitPrice` DECIMAL(10,2) UNSIGNED NOT NULL,
  `discountPorc` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `chargeTotal` DECIMAL(10,2) GENERATED ALWAYS AS (quantity*unitprice*(100-discountporc)/100) VIRTUAL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `sale_idx` (`saleId` ASC),
  INDEX `product_idx` (`productId` ASC),
  CONSTRAINT `sale`
    FOREIGN KEY (`saleId`)
    REFERENCES `Todo_Tecno`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productSold`
    FOREIGN KEY (`productId`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`productImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`productImages` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(45) NOT NULL,
  `productId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `product_idx` (`productId` ASC),
  CONSTRAINT `productOfImages`
    FOREIGN KEY (`productId`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`characteristics` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `productId` INT(10) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `product_idx` (`productId` ASC),
  CONSTRAINT `productOfCharacteristic`
    FOREIGN KEY (`productId`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`subCharacteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`subCharacteristics` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `characteristicId` INT(10) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `charasteristic_idx` (`characteristicId` ASC),
  CONSTRAINT `charasteristic`
    FOREIGN KEY (`characteristicId`)
    REFERENCES `Todo_Tecno`.`characteristics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`boughtTogether`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`boughtTogether` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `product1` INT(10) NOT NULL,
  `product2` INT(10) NOT NULL,
  `timesBoughtTogether` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `productA_idx` (`product1` ASC),
  INDEX `productB_idx` (`product2` ASC),
  CONSTRAINT `productA`
    FOREIGN KEY (`product1`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productB`
    FOREIGN KEY (`product2`)
    REFERENCES `Todo_Tecno`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Todo_Tecno`.`cuponsUsedByUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Todo_Tecno`.`cuponsUsedByUsers` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `userId` INT(10) NOT NULL,
  `cuponId` INT(10) NOT NULL,
  `usesCount` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  `deletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `whoUsedCupon_idx` (`userId` ASC),
  INDEX `cuponUsed_idx` (`cuponId` ASC),
  CONSTRAINT `whoUsedCupon`
    FOREIGN KEY (`userId`)
    REFERENCES `Todo_Tecno`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuponUsed`
    FOREIGN KEY (`cuponId`)
    REFERENCES `Todo_Tecno`.`discountCupons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
